// <auto-generated />
namespace travel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class travelv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(travelv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003281729065_travel-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
